# Generated by Django 5.2.8 on 2025-12-08 18:55

import django.core.validators
import django.db.models.deletion
import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]{7,15}$', 'Phone must contain only digits')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(90)])),
                ('address', models.TextField(blank=True, null=True)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=members.models.member_photo_path)),
                ('is_active', models.BooleanField(default=True)),
                ('member_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=members.models.qr_code_path)),
                ('gym', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='gyms.gym')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('gym', 'phone')},
            },
        ),
    ]
